### ISSUE TITLE
Questions about results

### ISSUE THREAD

**Issue by yuudee** [Daizy97/SaliencyAttack#2]
I tried running it according to the README, but I don't think the attack was successful (I set sample_size to 10).

The log shows "Attack succeeds" but when I compare the labels before and after the attack, they do not change or if they do change, the labels are similar.

For example
Before attack: ground beetle, carabid beetle
After: ground beetle, carabid beetle

Before attack: agaric
After attack: mushroom

**Comment by Daizy97** [comment]
Thanks for your question. "Attack suceeds" means the label has changed. Since we use ImageNet dataset, some classes are very similar, and are close in decision space. Thus, an image that is being perturbed tends to be first misclassified into its similar class.

For your example, I guess the first example is the 2nd image for untargeted attack. When I run the code, the result is normal and the image is successfully misclassified into "weevil".
